AWSTemplateFormatVersion: "2010-09-09"
Description: "Space Layer 000: Compute Services Management Policy"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Resources:
  ComputeServicesManagementPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-ComputeServicesManagement"
      Description: !Sub "Allows ${Environment} management access to EC2, ASG, ELB, Lambda, EKS, Launch Templates"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Launch Template
          - Sid: "LaunchTemplateManagementBase"
            Effect: "Allow"
            Action:
              - "ec2:CreateLaunchTemplate"
              - "ec2:DeleteLaunchTemplate"
              - "ec2:*LaunchTemplateVersion"
            Resource: "*"
          - Sid: "LaunchTemplateManagementScoped"
            Effect: "Allow"
            Action:
              - "ec2:ModifyLaunchTemplate"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          # Auto Scaling Group
          - Sid: "AutoScalingManagementBase"
            Effect: "Allow"
            Action:
              - "autoscaling:LaunchInstances"
            Resource: "*"
          - Sid: "AutoScalingManagementScoped"
            Effect: "Allow"
            Action:
              - "autoscaling:*AutoScalingGroup"
              - "autoscaling:*LoadBalancers"
              - "autoscaling:*Policy"
              - "autoscaling:*LoadBalancerTargetGroups"
              - "autoscaling:*Processes"
              - "autoscaling:*InstanceRefresh"
              - "autoscaling:*LaunchConfiguration"
              - "autoscaling:*Instances"
              - "autoscaling:*Standby"
              - "autoscaling:*LifecycleAction"
              - "autoscaling:*Tags"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          # EC2
          - Sid: "Ec2ManagementBase"
            Effect: "Allow"
            Action:
              - "ec2:*Tags"
              - "ec2:RunInstances"
            Resource: "*"
          - Sid: "Ec2ManagementScoped"
            Effect: "Allow"
            Action:
              - "ec2:AssociateIamInstanceProfile"
              - "ec2:RebootInstances"
              - "ec2:StartInstances"
              - "ec2:StopInstances"
              - "ec2:TerminateInstances"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          # Load Balancer
          - Sid: "LoadBalancerManagementBase"
            Effect: "Allow"
            Action:
              - "elasticloadbalancing:AddTags"
            Resource: "*"
          - Sid: "LoadBalancerManagementScopedByTags"
            Effect: "Allow"
            Action:
              - "elasticloadbalancing:RemoveTags"
              - "elasticloadbalancing:CreateLoadBalancer"
              - "elasticloadbalancing:DeleteLoadBalancer"
              - "elasticloadbalancing:ModifyLoadBalancer"
              - "elasticloadbalancing:CreateTrustStore"
              - "elasticloadbalancing:DeleteTrustStore"
              - "elasticloadbalancing:ModifyTrustStore"
              - "elasticloadbalancing:CreateListener"
              - "elasticloadbalancing:ModifyListener"
              - "elasticloadbalancing:AddListenerCertificates"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          - Sid: "LoadBalancerManagementScopedByPrefix"
            Effect: "Allow"
            Action:
              - "elasticloadbalancing:DeleteListener"
            Resource:
              - !Sub "arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:listener/app/${Environment}-*/*/*"
          # Target Groups
          - Sid: "TargetGroupsManagementBase"
            Effect: "Allow"
            Action:
              - "elasticloadbalancing:AddTags"
            Resource: "*"
          - Sid: "TargetGroupsManagementScopedByTags"
            Effect: "Allow"
            Action:
              - "elasticloadbalancing:CreateTargetGroup"
              - "elasticloadbalancing:DeregisterTargets"
              - "elasticloadbalancing:ModifyTargetGroup"
              - "elasticloadbalancing:RegisterTargets"
              - "elasticloadbalancing:ModifyTargetGroupAttributes"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          - Sid: "TargetGroupsManagementScopedByPrefix"
            Effect: "Allow"
            Action:
              - "elasticloadbalancing:DeleteTargetGroup"
            Resource: !Sub "arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:targetgroup/${Environment}-*/*"

Outputs:
  ComputeServicesManagementPolicyArn:
    Description: "ARN of the ComputeServicesManagementPolicy"
    Value: !Ref ComputeServicesManagementPolicy
    Export:
      Name: !Sub "${Environment}-ComputeServicesManagementPolicy-arn"
  ComputeServicesManagementPolicyId:
    Description: "ID of the ComputeServicesManagementPolicy"
    Value: !Ref ComputeServicesManagementPolicy
    Export:
      Name: !Sub "${Environment}-ComputeServicesManagementPolicy-id"
