AWSTemplateFormatVersion: "2010-09-09"
Description: "Core Layer 001: User Groups"

Resources:
  AdministratorsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "core-Administrators"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
  UsersGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "core-Users"
      ManagedPolicyArns:
        - Fn::ImportValue: "core-IamUserMfaSelfManagementPolicy-arn"
        - Fn::ImportValue: "core-AccountUserCredentialsSelfManagementPolicy-arn"

Outputs:
  UsersGroupArn:
    Description: "ARN of the UsersGroup"
    Value: !GetAtt UsersGroup.Arn
    Export:
      Name: "core-UsersGroup-arn"
  AdministratorsGroupArn:
    Description: "ARN of the AdministratorsGroup"
    Value: !GetAtt AdministratorsGroup.Arn
    Export:
      Name: "core-AdministratorsGroup-arn"
