AWSTemplateFormatVersion: "2010-09-09"
Description: "Core Layer 000: Network Services Discovery Policy"

Resources:
  NetworkServicesDiscoveryPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "core-NetworkServicesDiscovery"
      Description: "Allows read-only access to VPC, Subnets, Route Table, Internet Gateway, Network ACLs, VPN, Security Groups, Target Groups, Route53, CloudFront, API Gateway"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ec2:DescribeVpc*"
              - "ec2:DescribeAvailabilityZones*"
              - "ec2:DescribeDhcp*"
              - "ec2:DescribeSubnet*"
              - "ec2:DescribeRouteTable*"
              - "ec2:DescribeInternetGateway*"
              - "ec2:DescribeNetwork*"
              - "ec2:GetNetwork*"
              - "ec2:DescribeVpn*"
              - "ec2:DescribeSecurityGroup*"
              - "ec2:DescribeStaleSecurityGroup*"
              - "ec2:DescribeNat*"
              - "ec2:DescribeAddress*"
              - "ec2:DescribeEgressOnlyInternetGateways"
              - "ec2:GetSecurityGroupsForVpc"
              - "elasticloadbalancing:DescribeSSLPolicies"
              - "elasticloadbalancing:GetTrustStore*"
              - "elasticloadbalancing:DescribeTrustStore*"
              - "acm:List*"
              - "acm:Describe*"
              - "acm:Expor*"
              - "acm:Get*"
              - "acm-pca:Describe*"
              - "acm-pca:List*"
              - "acm-pca:Get*"
            Resource: "*"

Outputs:
  NetworkServicesDiscoveryPolicyArn:
    Description: "ARN of the NetworkServicesDiscoveryPolicy"
    Value: !GetAtt "NetworkServicesDiscoveryPolicy.PolicyArn"
    Export:
      Name: "core-NetworkServicesDiscoveryPolicy-arn"
  NetworkServicesDiscoveryPolicyId:
    Description: "ID of the NetworkServicesDiscoveryPolicy"
    Value: !GetAtt "NetworkServicesDiscoveryPolicy.PolicyId"
    Export:
      Name: "core-NetworkServicesDiscoveryPolicy-id"
