AWSTemplateFormatVersion: "2010-09-09"
Description: "Space Layer: Network Services Discovery Policy"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Resources:
  NetworkServicesDiscoveryPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-NetworkServicesDiscovery"
      Description: !Sub "Allows ${Environment} read only access to specified network services"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "DiscoveryBase"
            Effect: "Allow"
            Action:
              # VPCs
              - "ec2:DescribeVpcs"
              - "ec2:DescribeFlowLogs"
              - "ec2:DescribeAccountAttributes"
              - "ec2:DescribeAvailabilityZones"
              # Subnets
              - "ec2:DescribeSubnets"
              - "ec2:GetSubnetCidrReservations"
              # Route Tables
              - "ec2:DescribeRouteTables"
              # Internet Gateways
              - "ec2:DescribeInternetGateways"
              - "ec2:DescribeEgressOnlyInternetGateways"
              # DHCP
              - "ec2:DescribeDhcpOptions"
              # Elastic IPs
              - "ec2:DescribeAddresses"
              - "ec2:DescribeIpamPools"
              - "ec2:DescribePublicIpv4Pools"
              - "ec2:DescribeCoipPools"
              # Endpoints
              - "ec2:DescribeVpcEndpoints"
              # Instance Connect Endpoints
              - "ec2:DescribeInstanceConnectEndpoints"
              # Endpoint Services
              - "ec2:DescribeVpcEndpointServiceConfigurations"
              # NAT Gateways
              - "ec2:DescribeNatGateways"
              # VPC Peering Connections
              - "ec2:DescribeVpcPeeringConnections"
              # Network ACLs
              - "ec2:DescribeNetworkAcls"
              # Security Groups
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeSecurityGroupRules"
              - "ec2:DescribeSecurityGroupVpcAssociations"
              # Customer Gateways
              - "ec2:DescribeCustomerGateways"
              # Virtual Private Gateways
              - "ec2:DescribeVpnGateways"
              # Site-to-site VPN Connections
              - "ec2:DescribeVpnConnections"
              # Managed Prefix List
              - "ec2:DescribeManagedPrefixLists"
              # Route Servers
              - "ec2:DescribeRouteServers"
              # Network Interfaces
              - "ec2:DescribeNetworkInterfaces"
              # EC2 Instances
              - "ec2:DescribeInstances"
              # Internet Monitor
              - "internetmonitor:ListMonitors"
              # Resource Share Associatiions
              - "ram:GetResourceShareAssociations"
              # Route 53
              - "route53resolver:ListFirewallRuleGroupAssociations"
            Resource: "*"
          - Sid: "DiscoveryScopedByTags"
            Effect: "Allow"
            Action:
              # VPC
              - "ec2:DescribeVpcAttribute"
              - "ec2:GetSecurityGroupsForVpc"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment

  # Parameter Store Exports
  NetworkServicesDiscoveryPolicyArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/iac/space/identity/${Environment}-network-services-discovery-policy-arn"
      Description: "ARN for the NetworkServicesDiscoveryPolicy"
      Type: "String"
      Value: !GetAtt "NetworkServicesDiscoveryPolicy.PolicyArn"
