AWSTemplateFormatVersion: "2010-09-09"
Description: "Space Layer: Identity Services Management Policy"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Resources:
  IdentityServicesManagementPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-IdentityServicesManagement"
      Description: !Sub "Allows ${Environment} read only access to specified identity services"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "DiscoveryBase"
            Effect: "Allow"
            Action:
              # Summary
              - "iam:GetAccountSummary"
              - "iam:ListAccountAliases"
              # Groups
              - "iam:ListGroups"
              # Users
              - "iam:GetUser"
              - "iam:ListUsers"
              - "iam:ListGroupsForUser"
              - "iam:ListUserPolicies"
              - "iam:ListAttachedUserPolicies"
              - "iam:ListUserTags"
              # Roles
              - "iam:ListRoles"
              # Identity Providers
              - "iam:ListProviders"
              - "iam:ListOpenIDConnectProviders"
              - "iam:GetOpenIDConnectProvider"
              # Policies
              - "iam:ListPolicies"
              # Identity
              - "iam:GetAccountPasswordPolicy"
              - "iam:GetLoginProfile"
              # Access Keys
              - "iam:ListAccessKeys"
              - "iam:GetAccessKeyLastUsed"
              - "iam:ListMFADevices"
              - "iam:ListSigningCertificates"
              - "iam:ListSSHPublicKeys"
              - "iam:ListServiceSpecificCredentials"
              # Instance Profile
            Resource: "*"
          - Sid: "DiscoveryScoped"
            Effect: "Allow"
            Action:
              # Groups
              - "iam:GetGroup"
              - "iam:ListGroupPolicies"
              - "iam:ListAttachedGroupPolicies"
              # Roles
              - "iam:GetRole"
              - "iam:ListInstanceProfilesForRole"
              - "iam:ListRolePolicies"
              - "iam:ListAttachedRolePolicies"
              # Policies
              - "iam:ListPolicyVersions"
              - "iam:ListEntitiesForPolicy"
              - "iam:GenerateServiceLastAccessedDetails"
              # Instance Profiles
              - "iam:GetInstanceProfile"
              - "iam:ListInstanceProfilesForRole"
              - "iam:ListInstanceProfileTags"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:group/${Environment}-*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/${Environment}-*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/${Environment}-*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:instance-profile/${Environment}-*"
          - Sid: "ManagementScoped"
            Effect: "Allow"
            Action:
              # Groups
              - "iam:CreateGroup"
              - "iam:DeleteGroup"
              - "iam:AddUserToGroup"
              - "iam:RemoveUserFromGroup"
              - "iam:AttachGroupPolicy"
              - "iam:DetachGroupPolicy"
              # Roles
              - "iam:CreateRole"
              - "iam:DeleteRole"
              - "iam:AttachRolePolicy"
              - "iam:DetachRolePolicy"
              - "iam:TagRole"
              - "iam:UntagRole"
              - "iam:PassRole"
              # Policies
              - "iam:GetPolicy"
              - "iam:GetPolicyVersion"
              - "iam:CreatePolicy"
              - "iam:CreatePolicyVersion"
              - "iam:DeletePolicy"
              - "iam:DeletePolicyVersion"
              - "iam:TagPolicy"
              - "iam:UntagPolicy"
              # Instance Profiles
              - "iam:CreateInstanceProfile"
              - "iam:DeleteInstanceProfile"
              - "iam:AddRoleToInstanceProfile"
              - "iam:RemoveRoleFromInstanceProfile"
              - "iam:TagInstanceProfile"
              - "iam:UntagInstanceProfile"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:group/${Environment}-*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/${Environment}-*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/${Environment}-*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:instance-profile/${Environment}-*"
      Roles:
        - !Sub "{{resolve:ssm:/iac/space/identity/${Environment}-dev-ops-engineer-human-role-name}}"

  # Parameter Store Exports
  IdentityServicesManagementPolicyArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/iac/space/identity/${Environment}-identity-services-management-policy-arn"
      Description: "ARN for the IdentityServicesManagementPolicy"
      Type: "String"
      Value: !GetAtt "IdentityServicesManagementPolicy.PolicyArn"
