AWSTemplateFormatVersion: "2010-09-09"
Description: "Space Layer: Infrastructure Services Management Policy"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Resources:
  InfrastructureServicesManagementPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-InfrastructureServicesManagement"
      Description: !Sub "Allows ${Environment} read only access to specified infrastructure services"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "ManagementBase"
            Effect: "Allow"
            Action:
              # CloudFormation
              - "cloudformation:CreateChangeSet"
              - "cloudformation:ValidateTemplate"
            Resource: "*"
          - Sid: "DiscoveryScopedByPrefix"
            Effect: "Allow"
            Action:
              # CloudFormation
              - "cloudformation:CreateStack"
              - "cloudformation:DeleteStack"
              - "cloudformation:UpdateStack"
              - "cloudformation:RollbackStack"
              - "cloudformation:ExecuteChangeSet"
            Resource:
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*${Environment}*/*"
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*${Environment}*"
      Roles:
        - !Sub "{{resolve:ssm:/iac/space/identity/${Environment}-dev-ops-engineer-human-role-name}}"

  # Parameter Store Exports
  InfrastructureServicesManagementPolicyArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/iac/space/identity/${Environment}-infrastructure-services-management-policy-arn"
      Description: "ARN for the InfrastructureServicesManagementPolicy"
      Type: "String"
      Value: !GetAtt "InfrastructureServicesManagementPolicy.PolicyArn"
