AWSTemplateFormatVersion: "2010-09-09"
Description: "Serverless Office Hours Instance Scheduler Layer 001: Monitoring"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]
  Project:
    Type: String
    Description: "The project name to prefix resource names."

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Environment}-devops-instance-scheduler"
      RetentionInDays: 14
      Tags:
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: !Sub "${Project}"
        - Key: Layer
          Value: "001-iam-roles-000-base"

Outputs:
  LogGroupArn:
    Description: "ARN of the LogGroup"
    Value: !GetAtt LogGroup.Arn
    Export:
      Name: !Sub "${Environment}-instance-scheduler-LogGroup-arn"
  LogGroupName:
    Description: "Name of the LogGroup"
    Value: !Ref LogGroup
    Export:
      Name: !Sub "${Environment}-instance-scheduler-LogGroup-name"
