AWSTemplateFormatVersion: "2010-09-09"
Description: "Global Layer 000: Managed Policies"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Resources:
  AccountUserCredentialsSelfManagementPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "AccountUserCredentialsSelfManagement"
      Description: "Allows users to read Account Management service metadata."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowAccountInfoReadSpecific"
            Effect: Allow
            Action:
              - "account:GetAccountInformation"
            Resource: !Sub "arn:aws:account::${AWS::AccountId}:account"
  IamUserMfaSelfManagementPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "IAMUserMFASelfManagement"
      Description: "Allows users to manage their own MFA devices."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowIAMReadRequired"
            Effect: Allow
            Action:
              - "iam:ListMFADevices"
              - "iam:ListVirtualMFADevices"
            Resource: "*"

          - Sid: "AllowSelfMFADeviceManagement"
            Effect: Allow
            Action:
              - "iam:CreateVirtualMFADevice"
              - "iam:EnableMFADevice"
              - "iam:ResyncMFADevice"
              - "iam:DeactivateMFADevice"
              - "iam:DeleteVirtualMFADevice"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:user/${!aws:username}"
              - !Sub "arn:aws:iam::${AWS::AccountId}:mfa/*"
  IamPassRoleEc2Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-IAMPassRoleEC2"
      Description: "Allows users to assign specific IAM roles to EC2 instances to enable service-to-service permissions."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowEC2RoleDelegation"
            Effect: Allow
            Action: "iam:PassRole"
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Environment}-EC2*"
  SsmEnvironmentRestrictedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-SSMEnvironmentRestricted"
      Description: !Sub "Allows SSM Session Manager access only to ${Environment} instances."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "SSMConnectRestrictedToEnvironment"
            Effect: Allow
            Action:
              - "ssm:StartSession"
            Resource:
              - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          - Sid: "SSMGeneralActions"
            Effect: Allow
            Action:
              - "ssm:DescribeSessions"
              - "ssm:GetConnectionStatus"
              - "ssm:DescribeInstanceInformation"
              - "ssm:TerminateSession"
              - "ssm:ResumeSession"
            Resource: "*"
  DevOpsBasePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-DevOpsBase"
      Description: !Sub "Consolidated base DevOps permissions for ${Environment}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Management"
            Effect: Allow
            Action:
              # EC2 & VPC Management
              - "ec2:RunInstances"
              - "ec2:TerminateInstances"
              - "ec2:StopInstances"
              - "ec2:StartInstances"
              - "ec2:Associate*"
              - "ec2:Disassociate*"
              - "ec2:Create*"
              - "ec2:Delete*"
              - "ec2:Modify*"
              # S3 Management
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:CreateBucket"
              # CloudFormation Management
              - "cloudformation:CreateStack"
              - "cloudformation:UpdateStack"
              - "cloudformation:DeleteStack"
              - "cloudformation:ExecuteChangeSet"
              # SSM Management
              - "ssm:StartSession"
              - "ssm:PutParameter"
              - "ssm:DeleteParameter"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
              Bool:
                "aws:MultiFactorAuthPresent": "true"
          - Sid: "Discovery"
            Effect: Allow
            Action:
              - "ec2:Describe*"
              - "s3:ListAllMyBuckets"
              - "s3:GetBucket*"
              - "s3:ListBucket"
              - "cloudformation:DescribeStacks"
              - "cloudformation:ListStacks"
              - "cloudformation:GetTemplate*"
              - "cloudformation:DescribeStackEvents"
              - "cloudwatch:Describe*"
              - "cloudwatch:Get*"
              - "cloudwatch:List*"
              - "ssm:Describe*"
              - "ssm:Get*"
              - "ssm:List*"
            Resource: "*"

Outputs:
  IamUserMfaSelfManagementPolicyArn:
    Description: "ARN of the IamUserMfaSelfManagementPolicy"
    Value: !GetAtt "IamUserMfaSelfManagementPolicy.PolicyArn"
    Export:
      Name: "IamUserMfaSelfManagementPolicy-arn"
  IamUserMfaSelfManagementPolicyId:
    Description: "ID of the IamUserMfaSelfManagementPolicy"
    Value: !GetAtt "IamUserMfaSelfManagementPolicy.PolicyId"
    Export:
      Name: "IamUserMfaSelfManagementPolicy-id"
  AccountUserCredentialsSelfManagementArn:
    Description: "ARN of the AccountUserCredentialsSelfManagement"
    Value: !GetAtt "AccountUserCredentialsSelfManagementPolicy.PolicyArn"
    Export:
      Name: "AccountUserCredentialsSelfManagementPolicy-arn"
  AccountUserCredentialsSelfManagementId:
    Description: "ID of the AccountUserCredentialsSelfManagement"
    Value: !GetAtt "AccountUserCredentialsSelfManagementPolicy.PolicyId"
    Export:
      Name: "AccountUserCredentialsSelfManagementPolicy-id"
  IamPassRoleEc2PolicyArn:
    Description: "ARN of the IamPassRoleEc2Policy"
    Value: !GetAtt "IamPassRoleEc2Policy.PolicyArn"
    Export:
      Name: !Sub "${Environment}-IamPassRoleEc2Policy-arn"
  IamPassRoleEc2PolicyId:
    Description: "ID of the IamPassRoleEc2Policy"
    Value: !GetAtt "IamPassRoleEc2Policy.PolicyId"
    Export:
      Name: !Sub "${Environment}-IamPassRoleEc2Policy-id"
  SsmRestrictedPolicyArn:
    Description: "ARN of the IamPassRoleEc2Policy"
    Value: !Ref SsmEnvironmentRestrictedPolicy
    Export:
      Name: !Sub "${Environment}-SsmRestrictedPolicy-arn"
  SsmRestrictedPolicyId:
    Description: "ID of the IamPassRoleEc2Policy"
    Value: !Ref SsmEnvironmentRestrictedPolicy
    Export:
      Name: !Sub "${Environment}-SsmRestrictedPolicy-id"
  DevOpsBasePolicyArn:
    Description: "ARN of the DevOpsBasePolicy"
    Value: !Ref DevOpsBasePolicy
    Export:
      Name: !Sub "${Environment}-DevOpsBasePolicy-arn"
  DevOpsBasePolicyId:
    Description: "ID of the DevOpsBasePolicy"
    Value: !Ref DevOpsBasePolicy
    Export:
      Name: !Sub "${Environment}-DevOpsBasePolicy-id"
