AWSTemplateFormatVersion: "2010-09-09"
Description: "Global Layer 000: Managed Policies"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Resources:
  AccountUserCredentialsSelfManagementPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-AccountUserCredentialsSelfManagement"
      Description: "Allows users to read Account Management service metadata."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowAccountInfoReadSpecific"
            Effect: Allow
            Action:
              - "account:GetAccountInformation"
            Resource: !Sub "arn:aws:account::${AWS::AccountId}:account"
  IamUserMfaSelfManagementPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-IAMUserMFASelfManagement"
      Description: "Allows users to manage their own MFA devices."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowIAMReadRequired"
            Effect: Allow
            Action:
              - "iam:ListMFADevices"
              - "iam:ListVirtualMFADevices"
            Resource: "*"

          - Sid: "AllowSelfMFADeviceManagement"
            Effect: Allow
            Action:
              - "iam:CreateVirtualMFADevice"
              - "iam:EnableMFADevice"
              - "iam:ResyncMFADevice"
              - "iam:DeactivateMFADevice"
              - "iam:DeleteVirtualMFADevice"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:user/${!aws:username}"
              - !Sub "arn:aws:iam::${AWS::AccountId}:mfa/*"
  IamPassRoleEc2Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-IAMPassRoleEC2"
      Description: "Allows users to assign specific IAM roles to EC2 instances to enable service-to-service permissions."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowEC2RoleDelegation"
            Effect: Allow
            Action: "iam:PassRole"
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Environment}-EC2*"

Outputs:
  IamUserMfaSelfManagementPolicyArn:
    Description: "ARN of the IamUserMfaSelfManagementPolicy"
    Value: !GetAtt "IamUserMfaSelfManagementPolicy.PolicyArn"
    Export:
      Name: !Sub "${Environment}-IamUserMfaSelfManagementPolicy-arn"
  IamUserMfaSelfManagementPolicyId:
    Description: "ID of the IamUserMfaSelfManagementPolicy"
    Value: !GetAtt "IamUserMfaSelfManagementPolicy.PolicyId"
    Export:
      Name: !Sub "${Environment}-IamUserMfaSelfManagementPolicy-id"
  AccountUserCredentialsSelfManagementArn:
    Description: "ARN of the AccountUserCredentialsSelfManagement"
    Value: !GetAtt "AccountUserCredentialsSelfManagementPolicy.PolicyArn"
    Export:
      Name: !Sub "${Environment}-AccountUserCredentialsSelfManagementPolicy-arn"
  AccountUserCredentialsSelfManagementId:
    Description: "ID of the AccountUserCredentialsSelfManagement"
    Value: !GetAtt "AccountUserCredentialsSelfManagementPolicy.PolicyId"
    Export:
      Name: !Sub "${Environment}-AccountUserCredentialsSelfManagementPolicy-id"
  IamPassRoleEc2PolicyArn:
    Description: "ARN of the IamPassRoleEc2Policy"
    Value: !GetAtt "IamPassRoleEc2Policy.PolicyArn"
    Export:
      Name: !Sub "${Environment}-IamPassRoleEc2Policy-arn"
  IamPassRoleEc2PolicyId:
    Description: "ID of the IamPassRoleEc2Policy"
    Value: !GetAtt "IamPassRoleEc2Policy.PolicyId"
    Export:
      Name: !Sub "${Environment}-IamPassRoleEc2Policy-id"
