AWSTemplateFormatVersion: "2010-09-09"
Description: "Global Layer 002: User Groups"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Resources:
  AdministratorsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${Environment}-Administrators"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
  UsersGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "Users"
      ManagedPolicyArns:
        - Fn::ImportValue: "IamUserMfaSelfManagementPolicy-arn"
        - Fn::ImportValue: "AccountUserCredentialsSelfManagementPolicy-arn"
  DevOpsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${Environment}-DevOps"
      ManagedPolicyArns:
        - Fn::ImportValue: !Sub "${Environment}-DevOpsBasePolicy-arn"
        - Fn::ImportValue: !Sub "${Environment}-IamPassRoleEc2Policy-arn"
        - Fn::ImportValue: !Sub "${Environment}-SsmRestrictedPolicy-arn"

Outputs:
  AdministratorsGroupArn:
    Description: "ARN of the AdministratorsGroup"
    Value: !GetAtt AdministratorsGroup.Arn
    Export:
      Name: !Sub "${Environment}-AdministratorsGroup-arn"
  UsersGroupArn:
    Description: "ARN of the UsersGroup"
    Value: !GetAtt UsersGroup.Arn
    Export:
      Name: "UsersGroup-arn"
  DevOpsGroupArn:
    Description: "ARN of the DevOpsGroup"
    Value: !GetAtt DevOpsGroup.Arn
    Export:
      Name: !Sub "${Environment}-DevOpsGroup-arn"
