AWSTemplateFormatVersion: "2010-09-09"
Description: "Global Layer 002: User Groups"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Resources:
  AdministratorsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${Environment}-Administrators"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
  UsersGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${Environment}-Users"
      ManagedPolicyArns:
        - Fn::ImportValue: !Sub "${Environment}-IamUserMfaSelfManagementPolicy-arn"
        - Fn::ImportValue: !Sub "${Environment}-AccountUserCredentialsSelfManagementPolicy-arn"
  DevOpsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${Environment}-DevOps"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AmazonSSMFullAccess"
        - "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"
        - "arn:aws:iam::aws:policy/AmazonVPCFullAccess"
        - "arn:aws:iam::aws:policy/AWSCloudFormationFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchFullAccess"
        - "arn:aws:iam::aws:policy/IAMFullAccess"
        - "arn:aws:iam::aws:policy/IAMReadOnlyAccess"
        - Fn::ImportValue: !Sub "${Environment}-IamPassRoleEc2Policy-arn"

Outputs:
  AdministratorsGroupArn:
    Description: "ARN of the AdministratorsGroup"
    Value: !GetAtt AdministratorsGroup.Arn
    Export:
      Name: !Sub "${Environment}-AdministratorsGroup-arn"
  UsersGroupArn:
    Description: "ARN of the UsersGroup"
    Value: !GetAtt UsersGroup.Arn
    Export:
      Name: !Sub "${Environment}-UsersGroup-arn"
  DevOpsGroupArn:
    Description: "ARN of the DevOpsGroup"
    Value: !GetAtt DevOpsGroup.Arn
    Export:
      Name: !Sub "${Environment}-DevOpsGroup-arn"
