AWSTemplateFormatVersion: "2010-09-09"
Description: "Global Layer 004: Network Connectivity Resources"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]
  Region:
    Type: String
    Description: "The region where the resources will reside."

Resources:
  # Internet gateway
  MainInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-igw"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Project
          Value: "core"
        - Key: Layer
          Value: "004-network-connectivity"
  # VPC gateway attachment
  MainInternetGatewayVpcAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !ImportValue
        Fn::Sub: "${Environment}-MainVpc-arn"
      InternetGatewayId: !Ref MainInternetGateway
  # Routes
  MainPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: MainInternetGateway
    Properties:
      RouteTableId: !ImportValue
        Fn::Sub: "${Environment}-MainPublicRouteTable-arn"
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MainInternetGateway

Outputs:
  # Internet gateway
  MainInternetGatewayArn:
    Description: "ARN of the MainInternetGateway"
    Value: !Ref MainInternetGateway
    Export:
      Name: !Sub "${Environment}-MainInternetGateway-arn"
  # VPC gateway attacment
  MainInternetGatewayVpcAttachmentArn:
    Description: "ARN of the MainInternetGatewayVpcAttachment"
    Value: !Ref MainInternetGatewayVpcAttachment
    Export:
      Name: !Sub "${Environment}-MainInternetGatewayVpcAttachment-arn"
  # Routes
  MainPublicRouteArn:
    Description: "ARN of the MainPublicRoute"
    Value: !Ref MainPublicRoute
    Export:
      Name: !Sub "${Environment}-MainPublicRoute-arn"
