AWSTemplateFormatVersion: "2010-09-09"
Description: "Serverless Office Hours Instance Scheduler Layer 002: Compute"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]
  Project:
    Type: String
    Description: "The project name to prefix resource names."

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Environment}-devops-instance-scheduler"
      Role: !ImportValue
        Fn::Sub: "${Environment}-instance-scheduler-LambdaExecutionRole-arn"
      Code:
        ImageUri: !Sub
          - "${RepositoryUri}:${ImageTag}"
          - RepositoryUri: !ImportValue "core-InstanceSchedulerRepository-uri"
            ImageTag: latest
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
      PackageType: Image
      MemorySize: 128
      Timeout: 30
      EphemeralStorage:
        Size: 512
      Architectures:
        - x86_64
      RecursiveLoop: Terminate
      Tags:
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: !Sub "${Project}"
        - Key: Layer
          Value: "002-compute-000-base"

Outputs:
  LambdaFunctionArn:
    Description: "ARN of the Function"
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub "${Environment}-instance-scheduler-Function-arn"
