AWSTemplateFormatVersion: "2010-09-09"
Description: "Space Layer 003: Core Network"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]
  Region:
    Type: String
    Description: "The region where the resources will reside."

Resources:
  # VPC
  MainVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-vpc"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
        - Key: Layer
          Value: "003-network-core-000-base"
  # Subnets
  MainPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVpc
      CidrBlock: 10.0.0.0/20
      AvailabilityZone: !Sub "${Region}a"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-subnet-public1-${Region}a"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  MainPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVpc
      CidrBlock: 10.0.16.0/20
      AvailabilityZone: !Sub "${Region}b"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-subnet-public2-${Region}b"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
        - Key: Layer
          Value: "003-network-core-000-base"
  MainPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVpc
      CidrBlock: 10.0.128.0/20
      AvailabilityZone: !Sub "${Region}a"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-subnet-private1-${Region}a"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
        - Key: Layer
          Value: "003-network-core-000-base"
  MainPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVpc
      CidrBlock: 10.0.144.0/20
      AvailabilityZone: !Sub "${Region}b"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-subnet-private2-${Region}b"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
        - Key: Layer
          Value: "003-network-core-000-base"
  # Route tables
  MainPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVpc
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-rtb-public"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
        - Key: Layer
          Value: "003-network-core-000-base"
  MainPrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVpc
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-rtb-private1-${Region}a"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
        - Key: Layer
          Value: "003-network-core-000-base"
  MainPrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVpc
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-rtb-private2-${Region}b"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
        - Key: Layer
          Value: "003-network-core-000-base"
  # Subnet route table associations
  MainPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MainPublicSubnet1
      RouteTableId: !Ref MainPublicRouteTable
  MainPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MainPublicSubnet2
      RouteTableId: !Ref MainPublicRouteTable
  MainPrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MainPrivateSubnet1
      RouteTableId: !Ref MainPrivateRouteTable1
  MainPrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MainPrivateSubnet2
      RouteTableId: !Ref MainPrivateRouteTable2

Outputs:
  # VPC
  MainVpcId:
    Description: "ID of the MainVpc"
    Value: !GetAtt MainVpc.VpcId
    Export:
      Name: !Sub "${Environment}-MainVpc-id"
  MainVpcCidrBlock:
    Description: "CidrBlock of the MainVpc"
    Value: !GetAtt MainVpc.CidrBlock
    Export:
      Name: !Sub "${Environment}-MainVpc-cidr-block"
  # Subnets
  MainPublicSubnet1Id:
    Description: "ID of the MainPublicSubnet1"
    Value: !GetAtt MainPublicSubnet1.SubnetId
    Export:
      Name: !Sub "${Environment}-MainPublicSubnet1-id"
  MainPublicSubnet2Id:
    Description: "ID of the MainPublicSubnet2"
    Value: !GetAtt MainPublicSubnet2.SubnetId
    Export:
      Name: !Sub "${Environment}-MainPublicSubnet2-id"
  MainPrivateSubnet1Id:
    Description: "ID of the MainPrivateSubnet1"
    Value: !GetAtt MainPrivateSubnet1.SubnetId
    Export:
      Name: !Sub "${Environment}-MainPrivateSubnet1-id"
  MainPrivateSubnet2Id:
    Description: "ID of the MainPrivateSubnet2"
    Value: !GetAtt MainPrivateSubnet2.SubnetId
    Export:
      Name: !Sub "${Environment}-MainPrivateSubnet2-id"
  # Route tables
  MainPublicRouteTableId:
    Description: "ID of the MainPublicRouteTable"
    Value: !GetAtt MainPublicRouteTable.RouteTableId
    Export:
      Name: !Sub "${Environment}-MainPublicRouteTable-id"
  MainPrivateRouteTable1Id:
    Description: "ID of the MainPrivateRouteTable1"
    Value: !GetAtt MainPrivateRouteTable1.RouteTableId
    Export:
      Name: !Sub "${Environment}-MainPrivateRouteTable1-id"
  MainPrivateRouteTable2Id:
    Description: "ID of the MainPrivateRouteTable2"
    Value: !GetAtt MainPrivateRouteTable2.RouteTableId
    Export:
      Name: !Sub "${Environment}-MainPrivateRouteTable2-id"
  # Route table associations
  MainPublicSubnet1RouteTableAssociationId:
    Description: "ID of the MainPublicSubnet1RouteTableAssociation"
    Value: !GetAtt MainPublicSubnet1RouteTableAssociation.Id
    Export:
      Name: !Sub "${Environment}-MainPublicSubnet1RouteTableAssociation-id"
  MainPublicSubnet2RouteTableAssociationId:
    Description: "ID of the MainPublicSubnet2RouteTableAssociation"
    Value: !GetAtt MainPublicSubnet2RouteTableAssociation.Id
    Export:
      Name: !Sub "${Environment}-MainPublicSubnet2RouteTableAssociation-id"
  MainPrivateSubnet1RouteTableAssociationId:
    Description: "ID of the MainPrivateSubnet1RouteTableAssociation"
    Value: !GetAtt MainPrivateSubnet1RouteTableAssociation.Id
    Export:
      Name: !Sub "${Environment}-MainPrivateSubnet1RouteTableAssociation-id"
  MainPrivateSubnet2RouteTableAssociationId:
    Description: "ID of the MainPrivateSubnet2RouteTableAssociation"
    Value: !GetAtt MainPrivateSubnet2RouteTableAssociation.Id
    Export:
      Name: !Sub "${Environment}-MainPrivateSubnet2RouteTableAssociation-id"
