AWSTemplateFormatVersion: "2010-09-09"
Description: "Serverless Instance Scheduler Layer 002: Compute"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]
  Project:
    Type: String
    Description: "The project name to prefix resource names."

Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Environment}-devops-ec2-instance-scheduler"
      Code: !Sub "./projects/${Project}/functions/000-base/"
      Runtime: python3.14
      MemorySize: 128
      Timeout: 3
      Handler: main.main
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Role: !ImportValue
        Fn::Sub: "${Environment}-LambdaExecutionRole-arn"
      Architectures:
        - x86_64
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Tags:
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: !Sub "${Project}"
        - Key: Layer
          Value: "002-compute-000-base"

Outputs:
  FunctionArn:
    Description: "ARN of the Function"
    Value: !GetAtt Function.Arn
    Export:
      Name: !Sub "${Environment}-${Project}-Function-arn"
