AWSTemplateFormatVersion: "2010-09-09"
Description: "Two Tier Layer: Owner Access Consolidated"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Resources:
  OwnerHumanRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-TwoTierOwner"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": "true"
      Tags:
        - Key: Owner
          Value: "TwoTierOwners"
        - Key: Platform
          Value: "two-tier"
        - Key: Environment
          Value: !Ref Environment
        - Key: Layer
          Value: "identity-access-unit-owner"
  AssumeOwnerHumanRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-AssumeTwoTierOwnerHumanRole"
      Description: !Sub "Allows users to assume the ${Environment}-TwoTierOwner role."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Resource: !GetAtt OwnerHumanRole.Arn
  OwnersGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${Environment}-TwoTierOwners"
      ManagedPolicyArns:
        - !GetAtt AssumeOwnerHumanRolePolicy.PolicyArn

  # Parameter Store Exports
  OwnerHumanRoleArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/iac/project/two-tier/identity/${Environment}-owner-human-role-arn"
      Description: "ARN for the OwnerHumanRole"
      Type: "String"
      Value: !GetAtt "OwnerHumanRole.Arn"
  OwnerHumanRoleNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/iac/project/two-tier/identity/${Environment}-owner-human-role-name"
      Description: "Name for the OwnerHumanRole"
      Type: "String"
      Value: !Ref "OwnerHumanRole"
  AssumeOwnerHumanRolePolicyArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/iac/project/two-tier/identity/${Environment}-assume-owner-human-role-policy-arn"
      Description: "ARN for the AssumeOwnerHumanRolePolicy"
      Type: "String"
      Value: !GetAtt "AssumeOwnerHumanRolePolicy.PolicyArn"
  OwnersGroupArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/iac/project/two-tier/identity/${Environment}-owners-group-arn"
      Description: "ARN for the OwnersGroup"
      Type: "String"
      Value: !GetAtt "OwnersGroup.Arn"
  OwnersGroupNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/iac/project/two-tier/identity/${Environment}-owners-group-name"
      Description: "Name for the OwnersGroup"
      Type: "String"
      Value: !Ref "OwnersGroup"
