AWSTemplateFormatVersion: "2010-09-09"
Description: "Space Layer 002: Roles"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Resources:
  SsmHostManagementRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-SSMHostManagement"
      Description: "This IAM Instance Profile grants instances the minimum necessary permissions to register and function as managed nodes within AWS Systems Manager (SSM)."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
      Tags:
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  SsmHostManagementProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${Environment}-SSMHostManagementProfile"
      Roles:
        - !Ref SsmHostManagementRole

Outputs:
  SsmHostManagementRoleArn:
    Description: "ARN of the SsmHostManagementRole"
    Value: !GetAtt SsmHostManagementRole.Arn
    Export:
      Name: !Sub "${Environment}-SsmHostManagementRole-arn"
  SsmHostManagementRoleId:
    Description: "ID of the SsmHostManagementRole"
    Value: !GetAtt SsmHostManagementRole.RoleId
    Export:
      Name: !Sub "${Environment}-SsmHostManagementRole-id"
  SsmHostManagementProfileArn:
    Description: "ARN of the EC2SSMHostManagementProfile"
    Value: !GetAtt SsmHostManagementProfile.Arn
    Export:
      Name: !Sub "${Environment}-SsmHostManagementProfile-arn"
