AWSTemplateFormatVersion: "2010-09-09"
Description: "Space Layer 000: Managed Policies"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Conditions:
  IsProd: !Equals [!Ref Environment, "prod"]

Resources:
  IamPassRoleEc2Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-IAMPassRoleEC2"
      Description: "Allows users to assign specific IAM roles to EC2 instances to enable service-to-service permissions."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowEC2RoleDelegation"
            Effect: Allow
            Action: "iam:PassRole"
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Environment}-EC2*"
  SsmEnvironmentRestrictedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-SSMEnvironmentRestricted"
      Description: !Sub "Allows SSM Session Manager access only to ${Environment} instances."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "SSMConnectRestrictedToEnvironment"
            Effect: Allow
            Action:
              - "ssm:StartSession"
            Resource:
              - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          - Sid: "SSMGeneralActions"
            Effect: Allow
            Action:
              - "ssm:DescribeSessions"
              - "ssm:GetConnectionStatus"
              - "ssm:DescribeInstanceInformation"
              - "ssm:TerminateSession"
              - "ssm:ResumeSession"
            Resource: "*"
  DevOpsBasePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-DevOpsBase"
      Description: !Sub "Consolidated base DevOps permissions for ${Environment}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Discovery"
            Effect: Allow
            Action:
              # EC2 & VPC
              - "ec2:Describe*"
              # S3
              - "s3:ListAllMyBuckets"
              - "s3:GetBucket*"
              - "s3:ListBucket"
              # CloudFormation
              - "cloudformation:Describe*"
              - "cloudformation:List*"
              - "cloudformation:Get*"
              # Cloudwatch
              - "cloudwatch:Describe*"
              - "cloudwatch:Get*"
              - "cloudwatch:List*"
              # SSM
              - "ssm:Describe*"
              - "ssm:Get*"
              - "ssm:List*"
              # IAM
              - "iam:Get*"
              - "iam:List*"
              # Access analyzer
              - "access-analyzer:List*"
              - "access-analyzer:Get*"
              - "access-analyzer:Check*"
              - "access-analyzer:ValidatePolicy"
            Resource: "*"
          - Sid: "ServiceInitialiation"
            Effect: Allow
            Action:
              - "cloudformation:CreateChangeSet"
              - "cloudformation:ValidateTemplate"
              - "cloudformation:GetTemplateSummary"
            Resource: "*"
          - Sid: "ScopedManagementByTag"
            Effect: Allow
            Action:
              # EC2 & VPC
              - "ec2:RunInstances"
              - "ec2:TerminateInstances"
              - "ec2:StopInstances"
              - "ec2:StartInstances"
              - "ec2:Associate*"
              - "ec2:Disassociate*"
              - "ec2:Detach*"
              - "ec2:Create*"
              - "ec2:Delete*"
              - "ec2:Modify*"
              # S3
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:CreateBucket"
              # SSM
              - "ssm:StartSession"
              - "ssm:PutParameter"
              - "ssm:DeleteParameter"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          - Sid: "ScopedManagementByPattern"
            Effect: Allow
            Action:
              # CloudFormation
              - "cloudformation:CreateStack"
              - "cloudformation:UpdateStack"
              - "cloudformation:DeleteStack"
              - "cloudformation:ExecuteChangeSet"
              - "cloudformation:DescribeChangeSet"
              - "cloudformation:DeleteChangeSet"
              # IAM
              - "iam:CreatePolicy"
              - "iam:DeletePolicy"
              - "iam:CreatePolicy"
            Resource:
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*${Environment}*/*"
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*${Environment}*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/${Environment}-*"
              - !If [
                  IsProd,
                  !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/core-*/*",
                  !Ref "AWS::NoValue",
                ]
              - !If [
                  IsProd,
                  !Sub "arn:aws:iam::${AWS::AccountId}:policy/core-*",
                  !Ref "AWS::NoValue",
                ]

Outputs:
  IamPassRoleEc2PolicyArn:
    Description: "ARN of the IamPassRoleEc2Policy"
    Value: !GetAtt "IamPassRoleEc2Policy.PolicyArn"
    Export:
      Name: !Sub "${Environment}-IamPassRoleEc2Policy-arn"
  IamPassRoleEc2PolicyId:
    Description: "ID of the IamPassRoleEc2Policy"
    Value: !GetAtt "IamPassRoleEc2Policy.PolicyId"
    Export:
      Name: !Sub "${Environment}-IamPassRoleEc2Policy-id"
  SsmRestrictedPolicyArn:
    Description: "ARN of the SsmEnvironmentRestrictedPolicy"
    Value: !Ref SsmEnvironmentRestrictedPolicy
    Export:
      Name: !Sub "${Environment}-SsmRestrictedPolicy-arn"
  SsmRestrictedPolicyId:
    Description: "ID of the SsmEnvironmentRestrictedPolicy"
    Value: !Ref SsmEnvironmentRestrictedPolicy
    Export:
      Name: !Sub "${Environment}-SsmRestrictedPolicy-id"
  DevOpsBasePolicyArn:
    Description: "ARN of the DevOpsBasePolicy"
    Value: !Ref DevOpsBasePolicy
    Export:
      Name: !Sub "${Environment}-DevOpsBasePolicy-arn"
  DevOpsBasePolicyId:
    Description: "ID of the DevOpsBasePolicy"
    Value: !Ref DevOpsBasePolicy
    Export:
      Name: !Sub "${Environment}-DevOpsBasePolicy-id"
