AWSTemplateFormatVersion: "2010-09-09"
Description: "Space Layer 000: Managed Policies"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Conditions:
  IsProd: !Equals [!Ref Environment, "prod"]

Resources:
  IamPassRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-IAMPassRole"
      Description: "Allows users to assign specific IAM roles to EC2 instances to enable service-to-service permissions."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowEC2RoleDelegation"
            Effect: Allow
            Action: "iam:PassRole"
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Environment}-*"
  SsmEnvironmentRestrictedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-SSMEnvironmentRestricted"
      Description: !Sub "Allows SSM Session Manager access only to ${Environment} instances."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "SSMConnectRestrictedToEnvironment"
            Effect: Allow
            Action:
              - "ssm:StartSession"
            Resource:
              - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          - Sid: "SSMGeneralActions"
            Effect: Allow
            Action:
              - "ssm:DescribeSessions"
              - "ssm:GetConnectionStatus"
              - "ssm:DescribeInstanceInformation"
              - "ssm:TerminateSession"
              - "ssm:ResumeSession"
            Resource: "*"
  DevOpsBasePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-DevOpsBase"
      Description: !Sub "Consolidated base DevOps permissions for ${Environment}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # CloudFormation
          - Sid: "CloudFormationDiscovery"
            Effect: Allow
            Action:
              - "cloudformation:Describe*"
              - "cloudformation:List*"
              - "cloudformation:Get*"
              - "cloudformation:Validate*"
            Resource: "*"
          - Sid: "CloudFormationManagementBase"
            Effect: Allow
            Action:
              - "cloudformation:CreateChangeSet"
              - "cloudformation:ValidateTemplate"
              - "cloudformation:GetTemplateSummary"
            Resource: "*"
          - Sid: "CloudFormationManagementScoped"
            Effect: Allow
            Action:
              - "cloudformation:CreateStack"
              - "cloudformation:UpdateStack"
              - "cloudformation:DeleteStack"
              - "cloudformation:CreateChangeSet"
              - "cloudformation:ExecuteChangeSet"
            Resource:
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*${Environment}*/*"
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*${Environment}*"
              - !If [
                  IsProd,
                  !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/core-*/*",
                  !Ref "AWS::NoValue",
                ]
          # IAM
          - Sid: "IamDisovery"
            Effect: "Allow"
            Action:
              - "iam:Get*"
              - "iam:List*"
            Resource: "*"
          - Sid: "IamPolicyManagementScoped"
            Effect: "Allow"
            Action:
              - "iam:CreatePolicy*"
              - "iam:DeletePolicy*"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/${Environment}-*"
          # EC2 & Network
          - Sid: "NetworkEc2Discovery"
            Effect: "Allow"
            Action:
              - "ec2:Get*"
              - "ec2:List*"
              - "ec2:Describe*"
            Resource: "*"
          - Sid: "NetworkEc2ManagementBase"
            Effect: "Allow"
            Action:
              - "ec2:CreateTags"
              - "ec2:DeleteTags"
            Resource: "*"
          # VPC
          - Sid: "VpcManagementBase"
            Effect: "Allow"
            Action:
              - "ec2:CreateVpc"
              - "ec2:ModifyVpcAttribute"
            Resource: "*"
          - Sid: "VpcManagementScoped"
            Effect: "Allow"
            Action:
              - "ec2:DeleteVpc"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          # Subnet
          - Sid: "SubnetManagementBase"
            Effect: "Allow"
            Action:
              - "ec2:CreateSubnet"
              - "ec2:ModifySubnetAttribute"
            Resource: "*"
          - Sid: "SubnetManagementScoped"
            Effect: "Allow"
            Action:
              - "ec2:DeleteSubnet"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          # Route Table
          - Sid: "RouteTableManagementBase"
            Effect: "Allow"
            Action:
              - "ec2:CreateRouteTable"
            Resource: "*"
          - Sid: "RouteTableManagementScoped"
            Effect: "Allow"
            Action:
              - "ec2:DeleteRouteTable"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment
          # Subnet Route Table Association
          - Sid: "SubnetRouteTableAssociationManagementScoped"
            Effect: "Allow"
            Action:
              - "ec2:AssociateRouteTable"
              - "ec2:DissociateRouteTable"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Environment": !Ref Environment

Outputs:
  IamPassRolePolicyArn:
    Description: "ARN of the IamPassRolePolicy"
    Value: !GetAtt "IamPassRolePolicy.PolicyArn"
    Export:
      Name: !Sub "${Environment}-IamPassRolePolicy-arn"
  IamPassRolePolicyId:
    Description: "ID of the IamPassRolePolicy"
    Value: !GetAtt "IamPassRolePolicy.PolicyId"
    Export:
      Name: !Sub "${Environment}-IamPassRolePolicy-id"
  SsmRestrictedPolicyArn:
    Description: "ARN of the SsmEnvironmentRestrictedPolicy"
    Value: !Ref SsmEnvironmentRestrictedPolicy
    Export:
      Name: !Sub "${Environment}-SsmRestrictedPolicy-arn"
  SsmRestrictedPolicyId:
    Description: "ID of the SsmEnvironmentRestrictedPolicy"
    Value: !Ref SsmEnvironmentRestrictedPolicy
    Export:
      Name: !Sub "${Environment}-SsmRestrictedPolicy-id"
  DevOpsBasePolicyArn:
    Description: "ARN of the DevOpsBasePolicy"
    Value: !Ref DevOpsBasePolicy
    Export:
      Name: !Sub "${Environment}-DevOpsBasePolicy-arn"
  DevOpsBasePolicyId:
    Description: "ID of the DevOpsBasePolicy"
    Value: !Ref DevOpsBasePolicy
    Export:
      Name: !Sub "${Environment}-DevOpsBasePolicy-id"
