AWSTemplateFormatVersion: "2010-09-09"
Description: "Space Layer 003: Base Network Resources"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]
  Region:
    Type: String
    Description: "The region where the resources will reside."

Resources:
  # VPC
  MainVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-vpc"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  # Subnets
  MainPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVpc
      CidrBlock: 10.0.0.0/20
      AvailabilityZone: !Sub "${Region}a"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-subnet-public1-${Region}a"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  MainPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVpc
      CidrBlock: 10.0.16.0/20
      AvailabilityZone: !Sub "${Region}b"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-subnet-public2-${Region}b"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  MainPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVpc
      CidrBlock: 10.0.128.0/20
      AvailabilityZone: !Sub "${Region}a"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-subnet-private1-${Region}a"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  MainPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVpc
      CidrBlock: 10.0.144.0/20
      AvailabilityZone: !Sub "${Region}b"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-subnet-private2-${Region}b"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  # Route tables
  MainPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVpc
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-rtb-public"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  MainPrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVpc
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-rtb-private1-${Region}a"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  MainPrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVpc
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-rtb-private2-${Region}b"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  # Subnet route table associations
  MainPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MainPublicSubnet1
      RouteTableId: !Ref MainPublicRouteTable
  MainPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MainPublicSubnet2
      RouteTableId: !Ref MainPublicRouteTable
  MainPrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MainPrivateSubnet1
      RouteTableId: !Ref MainPrivateRouteTable1
  MainPrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MainPrivateSubnet2
      RouteTableId: !Ref MainPrivateRouteTable2
  # Network ACLs
  MainPublicNacl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref MainVpc
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-public-nacl"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  MainPrivateNacl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref MainVpc
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-private-nacl"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  # NACL Rules
  InboundPublicAllNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref MainPublicNacl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
  OutboundPublicAllNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref MainPublicNacl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
  InboundPrivateVpcAllNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref MainPrivateNacl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: 10.0.0.0/16
  InboundPrivateEphemeralNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref MainPrivateNacl
      RuleNumber: 110
      Protocol: 6
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      PortRange: { From: 1024, To: 65535 }
  OutboundPrivateAllNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref MainPrivateNacl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
  # Subnet NACL Associations
  PublicSubnet1NaclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref MainPublicSubnet1
      NetworkAclId: !Ref MainPublicNacl
  PublicSubnet2NaclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref MainPublicSubnet2
      NetworkAclId: !Ref MainPublicNacl
  PrivateSubnet1NaclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref MainPrivateSubnet1
      NetworkAclId: !Ref MainPrivateNacl
  PrivateSubnet2NaclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref MainPrivateSubnet2
      NetworkAclId: !Ref MainPrivateNacl

Outputs:
  # VPC
  MainVpcId:
    Description: "ID of the MainVpc"
    Value: !GetAtt MainVpc.VpcId
    Export:
      Name: !Sub "${Environment}-MainVpc-id"
  # Subnets
  MainPublicSubnet1Id:
    Description: "ID of the MainPublicSubnet1"
    Value: !GetAtt MainPublicSubnet1.SubnetId
    Export:
      Name: !Sub "${Environment}-MainPublicSubnet1-id"
  MainPublicSubnet2Id:
    Description: "ID of the MainPublicSubnet2"
    Value: !GetAtt MainPublicSubnet2.SubnetId
    Export:
      Name: !Sub "${Environment}-MainPublicSubnet2-id"
  MainPrivateSubnet1Id:
    Description: "ID of the MainPrivateSubnet1"
    Value: !GetAtt MainPrivateSubnet1.SubnetId
    Export:
      Name: !Sub "${Environment}-MainPrivateSubnet1-id"
  MainPrivateSubnet2Id:
    Description: "ID of the MainPrivateSubnet2"
    Value: !GetAtt MainPrivateSubnet2.SubnetId
    Export:
      Name: !Sub "${Environment}-MainPrivateSubnet2-id"
  # Route tables
  MainPublicRouteTableId:
    Description: "ID of the MainPublicRouteTable"
    Value: !GetAtt MainPublicRouteTable.RouteTableId
    Export:
      Name: !Sub "${Environment}-MainPublicRouteTable-id"
  MainPrivateRouteTable1Id:
    Description: "ID of the MainPrivateRouteTable1"
    Value: !GetAtt MainPrivateRouteTable1.RouteTableId
    Export:
      Name: !Sub "${Environment}-MainPrivateRouteTable1-id"
  MainPrivateRouteTable2Id:
    Description: "ID of the MainPrivateRouteTable2"
    Value: !GetAtt MainPrivateRouteTable2.RouteTableId
    Export:
      Name: !Sub "${Environment}-MainPrivateRouteTable2-id"
  # Route table associations
  MainPublicSubnet1RouteTableAssociationId:
    Description: "ID of the MainPublicSubnet1RouteTableAssociation"
    Value: !GetAtt MainPublicSubnet1RouteTableAssociation.Id
    Export:
      Name: !Sub "${Environment}-MainPublicSubnet1RouteTableAssociation-id"
  MainPublicSubnet2RouteTableAssociationId:
    Description: "ID of the MainPublicSubnet2RouteTableAssociation"
    Value: !GetAtt MainPublicSubnet2RouteTableAssociation.Id
    Export:
      Name: !Sub "${Environment}-MainPublicSubnet2RouteTableAssociation-id"
  MainPrivateSubnet1RouteTableAssociationId:
    Description: "ID of the MainPrivateSubnet1RouteTableAssociation"
    Value: !GetAtt MainPrivateSubnet1RouteTableAssociation.Id
    Export:
      Name: !Sub "${Environment}-MainPrivateSubnet1RouteTableAssociation-id"
  MainPrivateSubnet2RouteTableAssociationId:
    Description: "ID of the MainPrivateSubnet2RouteTableAssociation"
    Value: !GetAtt MainPrivateSubnet2RouteTableAssociation.Id
    Export:
      Name: !Sub "${Environment}-MainPrivateSubnet2RouteTableAssociation-id"
  # Network ACLs
  MainPublicNaclId:
    Description: "ID of the MainPublicNacl"
    Value: !GetAtt MainPublicNacl.Id
    Export:
      Name: !Sub "${Environment}-MainPublicNacl-id"
  MainPrivateNaclId:
    Description: "ID of the MainPrivateNacl"
    Value: !GetAtt MainPrivateNacl.Id
    Export:
      Name: !Sub "${Environment}-MainPrivateNacl-id"
  # NACL Rules
  InboundPublicAllNaclEntryId:
    Description: "ID of the InboundPublicAllNaclEntry"
    Value: !GetAtt InboundPublicAllNaclEntry.Id
    Export:
      Name: !Sub "${Environment}-InboundPublicAllNaclEntry-id"
  OutboundPublicAllNaclEntryId:
    Description: "ID of the OutboundPublicAllNaclEntry"
    Value: !GetAtt OutboundPublicAllNaclEntry.Id
    Export:
      Name: !Sub "${Environment}-OutboundPublicAllNaclEntry-id"
  InboundPrivateVpcAllNaclEntryId:
    Description: "ID of the InboundPrivateVpcAllNaclEntry"
    Value: !GetAtt InboundPrivateVpcAllNaclEntry.Id
    Export:
      Name: !Sub "${Environment}-InboundPrivateVpcAllNaclEntry-id"
  InboundPrivateEphemeralNaclEntryId:
    Description: "ID of the InboundPrivateEphemeralNaclEntry"
    Value: !GetAtt InboundPrivateEphemeralNaclEntry.Id
    Export:
      Name: !Sub "${Environment}-InboundPrivateEphemeralNaclEntry-id"
  OutboundPrivateAllNaclEntryId:
    Description: "ID of the OutboundPrivateAllNaclEntry"
    Value: !GetAtt OutboundPrivateAllNaclEntry.Id
    Export:
      Name: !Sub "${Environment}-OutboundPrivateAllNaclEntry-id"
  # Subnet NACL Associations
  PublicSubnet1NaclAssociationId:
    Description: "ID of the PublicSubnet1NaclAssociation"
    Value: !GetAtt PublicSubnet1NaclAssociation.AssociationId
    Export:
      Name: !Sub "${Environment}-PublicSubnet1NaclAssociation-id"
  PublicSubnet2NaclAssociationId:
    Description: "ID of the PublicSubnet2NaclAssociation"
    Value: !GetAtt PublicSubnet2NaclAssociation.AssociationId
    Export:
      Name: !Sub "${Environment}-PublicSubnet2NaclAssociation-id"
  PrivateSubnet1NaclAssociationId:
    Description: "ID of the PrivateSubnet1NaclAssociation"
    Value: !GetAtt PrivateSubnet1NaclAssociation.AssociationId
    Export:
      Name: !Sub "${Environment}-PrivateSubnet1NaclAssociation-id"
  PrivateSubnet2NaclAssociationId:
    Description: "ID of the PrivateSubnet2NaclAssociation"
    Value: !GetAtt PrivateSubnet2NaclAssociation.AssociationId
    Export:
      Name: !Sub "${Environment}-PrivateSubnet2NaclAssociation-id"
