AWSTemplateFormatVersion: "2010-09-09"
Description: "Space Layer 003: Network Connectivity"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]
  Region:
    Type: String
    Description: "The region where the resources will reside."

Resources:
  # Internet gateway
  MainInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main-igw"
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "space"
  # VPC gateway attachment
  MainInternetGatewayVpcAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !ImportValue
        Fn::Sub: "${Environment}-MainVpc-id"
      InternetGatewayId: !Ref MainInternetGateway
  # Routes
  MainPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: MainInternetGateway
    Properties:
      RouteTableId: !ImportValue
        Fn::Sub: "${Environment}-MainPublicRouteTable-id"
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MainInternetGateway

Outputs:
  # Internet gateway
  MainInternetGatewayId:
    Description: "ID of the MainInternetGateway"
    Value: !GetAtt MainInternetGateway.InternetGatewayId
    Export:
      Name: !Sub "${Environment}-MainInternetGateway-id"
  # VPC gateway attacment
  MainInternetGatewayVpcAttachmentId:
    Description: "ID of the MainInternetGatewayVpcAttachment"
    Value: !Ref MainInternetGatewayVpcAttachment
    Export:
      Name: !Sub "${Environment}-MainInternetGatewayVpcAttachment-id"
  # Routes
  MainPublicRouteId:
    Description: "ID of the MainPublicRoute"
    Value: !Ref MainPublicRoute
    Export:
      Name: !Sub "${Environment}-MainPublicRoute-id"
