AWSTemplateFormatVersion: "2010-09-09"
Description: "Core Layer 000: Monitoring Services Discovery Policy"

Resources:
  MonitoringServicesDiscoveryPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "core-MonitoringServicesDiscovery"
      Description: "Allows read-only access to Compute Optimizer, Access Analyzer, Free Tier Discovery, Cost Explorer, Cost Optimization"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "compute-optimizer:Get*"
              - "compute-optimizer:List*"
              - "compute-optimizer:Describe*"
              - "access-analyzer:Get*"
              - "access-analyzer:List*"
              - "access-analyzer:Check*"
              - "access-analyzer:Validate*"
              - "freetier:List*"
              - "freetier:Get*"
              - "ce:List*"
              - "ce:Get*"
              - "ce:Describe*"
              - "cost-optimization-hub:List*"
              - "cost-optimization-hub:Get*"
              - "servicecatalog:List*"
              - "servicecatalog:Get*"
              - "servicecatalog:Describe*"
              - "servicecatalog:Search*"
              - "servicecatalog:Scan*"
            Resource: "*"

Outputs:
  MonitoringServicesDiscoveryPolicyArn:
    Description: "ARN of the MonitoringServicesDiscoveryPolicy"
    Value: !GetAtt "MonitoringServicesDiscoveryPolicy.PolicyArn"
    Export:
      Name: "core-MonitoringServicesDiscoveryPolicy-arn"
  MonitoringServicesDiscoveryPolicyId:
    Description: "ID of the MonitoringServicesDiscoveryPolicy"
    Value: !GetAtt "MonitoringServicesDiscoveryPolicy.PolicyId"
    Export:
      Name: "core-MonitoringServicesDiscoveryPolicy-id"
