AWSTemplateFormatVersion: "2010-09-09"
Description: "Core Layer: Serverless Office Hours Instance Scheduler ECR Repository"

Resources:
  InstanceSchedulerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "serverless-office-hours-instance-scheduler"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: LambdaECRImageRetrievalPolicy
            Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action:
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images older than 14 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 14
                },
                "action": { "type": "expire" }
              },
              {
                "rulePriority": 2,
                "description": "Keep only the last 5 tagged images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags:
        - Key: Owner
          Value: "DevOps"
        - Key: Platform
          Value: "core"
        - Key: Layer
          Value: "infrastructure-ecr-repository-serverless-office-hours-instance-scheduler"

  # Parameter Store Exports
  InstanceSchedulerRepositoryArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/iac/core/infrastructure/instance-scheduler-repository-arn"
      Description: "ARN for the InstanceSchedulerRepository"
      Type: "String"
      Value: !GetAtt "InstanceSchedulerRepository.Arn"
